### ISSUE TITLE
Toolbar does not appear when selecting from middle to end.

### ISSUE THREAD

**Issue by muzzwood** [modxcms/fred-rte-tinymce#6] opened 2018-11-01 01:46 UTC
The TinyMCE toolbar doesn't appear if text is selected from the middle to the end of the text block. 
Works fine the other way.
See gif:
![selecttext](https://user-images.githubusercontent.com/5160368/47827779-bb402980-ddba-11e8-87f8-44ad3dfcc487.gif)

**Comment by theboxer** [comment] 2019-01-30 15:28
It's most likely caused by ending the select out of the tinymce area, which probably causes the field & editor to loose focus. I'm not sure how to fix this.

**Comment by matdave** [comment] 2021-03-29 21:51
This is fixed by adding a setting for `selection_toolbar`

**Closed as completed by matdave** 2021-03-29 21:51 UTC
Labels: bug
